// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADZnAMh0Ip8a90xbPnQQqD7JRWlTCMU0k',
    appId: '1:1064089244599:web:057c80f45f89fe8e5f8e32',
    messagingSenderId: '1064089244599',
    projectId: 'quizapp-a4be5',
    authDomain: 'quizapp-a4be5.firebaseapp.com',
    storageBucket: 'quizapp-a4be5.appspot.com',
    measurementId: 'G-26SC6BJFBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZodtP4jAWMpKdwTUlCjp2nGEe6jqWsJI',
    appId: '1:1064089244599:android:b7f2b1dff2fff0955f8e32',
    messagingSenderId: '1064089244599',
    projectId: 'quizapp-a4be5',
    storageBucket: 'quizapp-a4be5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxWyvqx2MdMJt0Bntjy0CMeXKXLXLoROI',
    appId: '1:1064089244599:ios:ffdff1ea019b61c95f8e32',
    messagingSenderId: '1064089244599',
    projectId: 'quizapp-a4be5',
    storageBucket: 'quizapp-a4be5.appspot.com',
    iosBundleId: 'com.example.adminapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxWyvqx2MdMJt0Bntjy0CMeXKXLXLoROI',
    appId: '1:1064089244599:ios:508fee8c1c4b2fa95f8e32',
    messagingSenderId: '1064089244599',
    projectId: 'quizapp-a4be5',
    storageBucket: 'quizapp-a4be5.appspot.com',
    iosBundleId: 'com.example.adminapp.RunnerTests',
  );
}
